// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjI80BmdvR_hK-KBFkGhd57knjGVVFuCM',
    appId: '1:182958874757:android:08afed0369ff799043c9ec',
    messagingSenderId: '182958874757',
    projectId: 'day-3435d',
    storageBucket: 'day-3435d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB97yRfJFdUkwA9Tvvknc8JMkji441N9Yg',
    appId: '1:182958874757:ios:365fe71c201a8ea043c9ec',
    messagingSenderId: '182958874757',
    projectId: 'day-3435d',
    storageBucket: 'day-3435d.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJLSWdHoOESMVVWjEa_zBcYcxcrltXsX4',
    appId: '1:182958874757:web:2577494befed3be443c9ec',
    messagingSenderId: '182958874757',
    projectId: 'day-3435d',
    authDomain: 'day-3435d.firebaseapp.com',
    storageBucket: 'day-3435d.firebasestorage.app',
    measurementId: 'G-NMWK5D7CR5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB97yRfJFdUkwA9Tvvknc8JMkji441N9Yg',
    appId: '1:182958874757:ios:365fe71c201a8ea043c9ec',
    messagingSenderId: '182958874757',
    projectId: 'day-3435d',
    storageBucket: 'day-3435d.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJLSWdHoOESMVVWjEa_zBcYcxcrltXsX4',
    appId: '1:182958874757:web:fb1ea7fe8a4ffef343c9ec',
    messagingSenderId: '182958874757',
    projectId: 'day-3435d',
    authDomain: 'day-3435d.firebaseapp.com',
    storageBucket: 'day-3435d.firebasestorage.app',
    measurementId: 'G-KY0GCZPWR4',
  );

}